### ISSUE TITLE
issue running the tool

### ISSUE THREAD

**Issue by c4ir0** [Roni-Carta/cf-bypass#6]
hey,
I have a problem with the running the very nice tool, do I miss sth ?
and **thx** 

![Capture](https://user-images.githubusercontent.com/108268587/192165994-3bfa9afb-ef52-4cf6-934a-33823e5a0db7.JPG)

**Comment by Roni-Carta** [comment]
Hi ! 

You need to run `bash install.sh` if you want to install the Docker Image in your system and use the allias to pipe your targets. 

Hopefully it helps :D

**Comment by c4ir0** [comment]
> Hi !
> 
> You need to run `bash install.sh` if you want to install the Docker Image in your system and use the allias to pipe your targets.
> 
> Hopefully it helps :D

1 As u can see my dear friend I run the image but still requires sec_trails_api_key despite it's provided (see num 2 ) that's a problem

**Comment by c4ir0** [comment]
> Hi !
> 
> You need to run `bash install.sh` if you want to install the Docker Image in your system and use the allias to pipe your targets.
> 
> Hopefully it helps :D

Hey Lupin, I found the solution somehow it was trivial all what was required is to run ` ./install `as root  kindly edit this in the installation guide to be `$ chmod u+x install.sh && sudo  ./install.sh` 👍 
[https://github.com/Roni-Carta/cf-bypass#install](url)



![1](https://user-images.githubusercontent.com/108268587/192297869-4211816c-c1dc-4d0e-aa71-a3235a65f93b.JPG)
